program: main.py
name: "Sweep Example (w/ FM)"
project: book-rating-prediction
method: bayes
metric:
    goal: minimize
    name: 'Valid RMSE'
description: |- 
    Add notes here if needed.
    Can be multi-line.
    Used as the wandb description.

parameters:
    config:
        value: ''
    predict:
        value: False
    checkpoint:
        value: ''
    device:
        value: cuda
    model:
        value: FM
    wandb:
        value: True
    wandb_project:
        value: 'book-rating-prediction'
    run_name:
        value: ''
    
    seed:
        values: [0, 1, 2, 3, 4]

    model_args:
        parameters:
            FM:
                parameters:
                    datatype:
                        value: context
                    embed_dim:
                        values: [8, 16, 32]

    dataset:
        parameters:
            data_path:
                value: data/
            valid_ratio:
                value: 0.2

    dataloader:
        parameters:
            batch_size:
                values: [512, 1024, 2048]
            shuffle:
                value: True
            num_workers:
                value: 0

    optimizer:
        parameters:
            type:
                value: Adam
            args:
                parameters:
                    lr:
                        min: 1e-4
                        max: 1e-2
                    weight_decay:
                        min: 1e-6
                        max: 1e-3
                    amsgrad:
                        values: [True, False]

    loss:
        value: RMSELoss
    
    lr_scheduler:
        parameters:
            use:
                values: [True, False]
            type:
                values: [ReduceLROnPlateau, StepLR]
            args:
                parameters:
                    mode:
                        value: min
                    factor:
                        value: 0.1
                    patience:
                        value: 5
                    cooldown:
                        value: 1
                    step_size:
                        value: 10
                    gamma:
                        value: 0.1

    metrics:
        value: [RMSELoss, MAELoss, MSELoss]

    train:
        parameters:
            epochs:
                value: 20
            log_dir:
                value: saved/log
            ckpt_dir:
                value: saved/checkpoint    
            submit_dir:
                value: saved/submit
            save_best_model:
                value: True
            resume:
                value: False
            resume_path:
                value: ''
