_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.5
            "6": 4.46.1
            "8":
                - 5
            "12": 0.18.5
            "13": darwin-arm64
config:
    value: config/config_baseline.yaml
dataloader:
    value:
        batch_size: 1024
        num_workers: 0
        shuffle: true
dataset:
    value:
        data_path: src/data/
        valid_ratio: 0.2
device:
    value: cuda
loss:
    value: RMSELoss
lr_scheduler:
    value:
        use: false
memo:
    value: |-
        남겨둘 메모가 있다면 여기에.
        여러 줄로도 작성 가능
        wandb 사용 시 wandb의 description으로 사용됩니다.
metrics:
    value:
        - MSELoss
        - MAELoss
        - RMSELoss
model:
    value: FM
model_args:
    value:
        FM:
            datatype: context
            embed_dim: 16
optimizer:
    value:
        args:
            amsgrad: false
            lr: 0.005
            weight_decay: 0.0001
        type: Adam
predict:
    value: false
run_name:
    value: ""
seed:
    value: 0
train:
    value:
        ckpt_dir: saved/checkpoint
        epochs: 20
        log_dir: saved/log
        resume: false
        save_best_model: true
        submit_dir: saved/submit
wandb:
    value: true
wandb_project:
    value: book-rating-prediction
